CREATE DATABASE Cua_hang_thuc_an_nhanh;
USE Cua_hang_thuc_an_nhanh;

CREATE TABLE ChucVu (
    Ma_CV CHAR(10) PRIMARY KEY,
    Ten_CV NVARCHAR(50) NOT NULL
);

CREATE TABLE TaiKhoan (
    Ma_TK CHAR(10) PRIMARY KEY,
    Ma_CV CHAR(10) NOT NULL,
    Ten_TK VARCHAR(255) NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Sdt VARCHAR(20) NOT NULL,
    CONSTRAINT FK_MA_CV_IN_TaiKhoan FOREIGN KEY (Ma_CV) REFERENCES ChucVu(Ma_CV)
);


CREATE TABLE DanhSach_LoaiSP (
    Ma_LoaiSP CHAR(10) PRIMARY KEY,
    Ten_LoaiSP NVARCHAR(100) NOT NULL
);

CREATE TABLE DanhSach_NhomSP (
    Ma_NhomSP CHAR(10) PRIMARY KEY,
    Ten_NhomSP NVARCHAR(100) NOT NULL
);

CREATE TABLE DanhSach_SanPham(
    Ma_SP CHAR(10) PRIMARY KEY,
    Ma_LoaiSP CHAR(10) NOT NULL,
    Ma_NhomSP CHAR(10) NOT NULL,
    Ten_SP NVARCHAR(100) NOT NULL,
    DonGia INT NOT NULL,
    GhiChu NVARCHAR(255),
    Ten_HinhSP VARCHAR(255),
    CONSTRAINT FK_Ma_LoaiSP_IN_DanhSach_SanPham FOREIGN KEY (Ma_LoaiSP) REFERENCES DanhSach_LoaiSP(Ma_LoaiSP),
    CONSTRAINT FK_Ma_NhomSP_IN_DanhSach_SanPham FOREIGN KEY (Ma_NhomSP) REFERENCES DanhSach_NhomSP(Ma_NhomSP)
);




CREATE TABLE DanhSach_HinhSP (
    Ma_HinhSP CHAR(10) PRIMARY KEY,
    Ma_SP CHAR(10) NOT NULL,
    Ten_HinhSP VARCHAR(255) NOT NULL,
    CONSTRAINT FK_Ma_SP_IN_DanhSach_HinhSP FOREIGN KEY (Ma_SP) REFERENCES DanhSach_SanPham(Ma_SP)
);

CREATE TABLE DanhSach_PhanHoi (
    Ma_PhanHoi CHAR(10) PRIMARY KEY,
    Ten NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Sdt VARCHAR(20) NOT NULL,
    NoiDung TEXT NOT NULL
);

CREATE TABLE DanhSach_HoaDon (
    Ma_HD CHAR(10) PRIMARY KEY,
    Ma_TK CHAR(10) NOT NULL,
    Ten_NguoiMua NVARCHAR(25) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Sdt VARCHAR(20) NOT NULL,
    DiaChi_NguoiMua NVARCHAR(255) NOT NULL,
    NgayLap_HoaDon DATETIME,
    TinhTrang VARCHAR(20) NOT NULL,
    GhiChu NVARCHAR(255),
    CONSTRAINT FK_Ma_TK_IN_DanhSach_HoaDon FOREIGN KEY (Ma_TK) REFERENCES TaiKhoan(Ma_TK)
);

CREATE TABLE ChiTiet_HoaDon (
    Ma_CTHD CHAR(10) PRIMARY KEY,
    Ma_HD CHAR(10) NOT NULL,
    Ma_SP CHAR(10) NOT NULL,
    SoLuong INT NOT NULL,
    DonGia INT NOT NULL,
    CONSTRAINT FK_Ma_HD_IN_ChiTiet_HoaDon FOREIGN KEY (Ma_HD) REFERENCES DanhSach_HoaDon(Ma_HD),
    CONSTRAINT FK_MD_SP_IN_ChiTiet_HoaDon FOREIGN KEY (Ma_SP) REFERENCES DanhSach_SanPham(Ma_SP)
);

